"""Concatenate src/ back into game/index.html.

voxelbit ships as ONE self-contained file — double-click start.bat, no build step for
the player, no dependencies. That has not changed. What changed is that the 16k-line
file is no longer what you EDIT: src/ holds it as ~78 ordered fragments so several
people (or several agents) can work on different subsystems at once without landing in
the same file.

  src/manifest.txt   the order. This file IS the architecture — the fragments are
                     concatenated top to bottom exactly as listed, nothing is sorted,
                     nothing is inferred from the directory names.
  game/index.html    a BUILD ARTIFACT. Never edit it; bundle.py overwrites it.

A fragment is a slice of text, not a module: no imports, no exports, no scope of its
own. Everything from core/boot.js to main/99-close.js lives inside the single
`(async () => { ... })()` that core/boot.js opens and main/99-close.js closes, so a
fragment may freely use anything declared in a fragment above it — exactly as the one
big file did. That is the point: the split is provably behaviour-neutral, because
concatenation reproduces the original bytes.

One fragment is not written by hand: src/assets/vox-index.js is a list of every .vox
under game/assets, refreshed from a walk of that tree on every build. See vox_index().

  python tools/bundle.py            refresh the asset index, rebuild game/index.html
  python tools/bundle.py --check    diff both against disk, write nothing
"""
import os, sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
SRC = os.path.join(ROOT, 'src')
OUT = os.path.join(ROOT, 'game', 'index.html')
ASSETS = os.path.join(ROOT, 'game', 'assets')
VOX_FRAG = 'assets/vox-index.js'                 # GENERATED - see vox_index()


def manifest():
    """Ordered fragment paths. Blank lines and # comments are ignored."""
    with open(os.path.join(SRC, 'manifest.txt'), encoding='utf8') as f:
        return [ln.strip() for ln in f if ln.strip() and not ln.startswith('#')]


VOX_HEAD = """\
  // ── EVERY .vox UNDER game/assets ── GENERATED BY tools/bundle.py. Do not edit: the next build
  // overwrites the whole file from a walk of the asset tree.
  //
  // WHY THIS EXISTS. There is no directory listing over HTTP, so the game cannot discover its own art:
  // every loader in assets/ names the files it wants, one string at a time, and an asset nobody wrote a
  // loader for is unreachable from inside the running page. /spawn and /locate are supposed to reach ALL
  // of it, so the build - which already walks src/ - walks game/assets too and writes the answer down
  // here. Add, rename or delete a .vox and the next `python tools/bundle.py` (which the pre-commit hook
  // runs for you) carries the change into the game; there is no second list anybody has to remember.
  // The other established trick, "fetch 00, 01, 02 ... until one 404s", is how the FRAME loaders find a
  // sequence length and is right for that - but it can only walk a numbered run inside a folder whose
  // name is already known, which is exactly the thing that is not known here.
  //
  // FORMAT: one entry per FOLDER, "<dir>:<name>,<name>,..." joined with ';'. Names keep their real case
  // (the fetch URL is case-sensitive) and drop the .vox; the empty dir is game/assets itself. Grouping by
  // folder is what makes this %(chars)s characters instead of the %(flat)s the flat paths cost. Folders are emitted
  // parent-first, siblings in order, so every subtree is a CONTIGUOUS run - ui/console.js relies on that to
  // answer "how many files are under life/tropical_life/pelican" without a second table. It is unpacked
  // lazily, on the first command that needs it, so the boot pays nothing for it.
  const VOXDEX = [                                     // %(files)s files in %(dirs)s folders
"""


def vox_index():
    """The text of src/assets/vox-index.js, derived from game/assets.

    Parent-first, siblings sorted: os.walk is top-down and dirnames is sorted in place, so a
    folder's whole subtree lands in one unbroken run of entries. console.js counts on it.
    """
    groups = []
    for dirpath, dirnames, files in os.walk(ASSETS):
        dirnames.sort(key=str.lower)
        names = sorted((f[:-4] for f in files if f[-4:].lower() == '.vox'), key=str.lower)
        if not names:
            continue
        rel = os.path.relpath(dirpath, ASSETS).replace(os.sep, '/')
        rel = '' if rel == '.' else rel
        for n in [rel] + names:
            if any(c in n for c in ',;:\'\\'):
                sys.exit('vox-index: ' + rel + '/' + n + " cannot be packed - a path may not "
                         "contain , ; : ' or a backslash. Rename the file.")
        groups.append((rel, names))
    rows = ["    '" + d + ':' + ','.join(ns) + "'," for d, ns in groups]
    nfile = sum(len(ns) for _, ns in groups)
    flat = sum(len(d) + len(n) + 2 for d, ns in groups for n in ns)
    chars = sum(len(r) - 7 for r in rows) + max(0, len(rows) - 1)   # 4 indent + 2 quotes + comma
    body = VOX_HEAD % {'files': nfile, 'dirs': len(groups), 'chars': chars, 'flat': flat}
    return body + '\n'.join(rows) + "\n  ].join(';');\n"


def refresh_vox_index(write):
    """Bring the generated fragment back in step with the asset tree. Returns True if it moved."""
    path = os.path.join(SRC, VOX_FRAG.replace('/', os.sep))
    want = vox_index().encode('utf8')                # LF only, like every other fragment
    have = open(path, 'rb').read() if os.path.exists(path) else None
    if have == want:
        return False
    if write:
        with open(path, 'wb') as f:
            f.write(want)
    return True


MODULE_MARK = b'// @module'


def wrap_module(rel, body):
    """Give one fragment its own scope.

    A fragment that opens with

        // @module
        // @exports foo, bar

    is wrapped in an IIFE that returns exactly those names, and the shared scope picks
    them up by destructuring. Everything else it declares becomes invisible to the other
    77 fragments - which is the point: two agents can then both invent `edIdx` without
    the merge being a SyntaxError and a black screen.

    The body is emitted byte-for-byte, so nothing inside the module changes; only what
    escapes it does. Names arrive in the shared scope as ordinary consts at the module's
    own position, so every use below it reads exactly as before, at the same cost.

    An exported `let` that other fragments ASSIGN cannot go through here - the shared
    scope would get a const copy and the writes would land nowhere. lint-vb.py check 10
    refuses that case rather than letting it become a silent bug.
    """
    NL = b'\n'
    lines = body.split(NL, 2)
    if len(lines) < 2 or not lines[1].strip().startswith(b'// @exports'):
        sys.exit(rel + ': has "// @module" but no "// @exports ..." line after it')
    names = [n.strip() for n in lines[1].split(b'// @exports', 1)[1].split(b',') if n.strip()]
    if not names:
        sys.exit(rel + ': "// @exports" lists no names')
    slug = rel.rsplit('.', 1)[0].replace('/', '_').replace('-', '_').encode()
    lst = b', '.join(names)
    return (b'  const __m_' + slug + b' = (() => {' + NL
            + body
            + b'    return { ' + lst + b' };' + NL
            + b'  })();' + NL
            + b'  const { ' + lst + b' } = __m_' + slug + b';' + NL)


def build():
    """The whole build: read every fragment in order, join the bytes.

    Binary throughout, and no separator — a fragment already ends in its own newline.
    Anything else (text mode, os.linesep, an added '\n') would rewrite line endings on
    Windows and silently break the byte-identical guarantee this file exists to hold.

    A fragment marked `// @module` is wrapped in its own scope on the way through; every
    other fragment is emitted verbatim, exactly as before.
    """
    out = bytearray()
    for rel in manifest():
        path = os.path.join(SRC, rel.replace('/', os.sep))
        if not os.path.exists(path):
            sys.exit('missing fragment: ' + rel + '  (listed in src/manifest.txt)')
        with open(path, 'rb') as f:
            body = f.read()
        out += wrap_module(rel, body) if body.lstrip().startswith(MODULE_MARK) else body
    return bytes(out)


def main():
    # The asset index is refreshed FIRST, so build() stays what it has always been: a byte-for-byte
    # concatenation of what is on disk. lint-vb.py's check 7 imports build() and would otherwise be
    # writing to src/ as a side effect of a read-only check.
    check = '--check' in sys.argv
    moved = refresh_vox_index(not check)
    if moved and check:
        print('STALE  src/' + VOX_FRAG + ' does not match game/assets - run: python tools/bundle.py')
    elif moved:
        print('built  src/' + VOX_FRAG + '  (game/assets changed)')

    built = build()
    old = open(OUT, 'rb').read() if os.path.exists(OUT) else None

    if check:
        if old == built:
            print('OK  game/index.html matches src/ ({:,} bytes)'.format(len(built)))
            return 1 if moved else 0             # ...but a stale asset index is still a stale build
        print('DIFFERS  src/ rebuilds to {:,} bytes, game/index.html is {:,}'
              .format(len(built), len(old) if old else 0))
        if old:                                  # first differing line, so the report is actionable
            a, b = old.split(b'\n'), built.split(b'\n')
            for i in range(min(len(a), len(b))):
                if a[i] != b[i]:
                    print('  first difference at line', i + 1)
                    print('    on disk:', a[i][:100])
                    print('    rebuilt:', b[i][:100])
                    break
            else:
                print('  one is a prefix of the other: {} vs {} lines'.format(len(a), len(b)))
        return 1

    if old == built:
        print('unchanged  game/index.html ({:,} bytes)'.format(len(built)))
        return 0
    with open(OUT, 'wb') as f:
        f.write(built)
    print('built  game/index.html  {:,} bytes from {} fragments'.format(len(built), len(manifest())))
    return 0


if __name__ == '__main__':
    sys.exit(main())
