"""Write docs/commits.md -- the commit tree, generated from git.

Run it from anywhere in the repo:  py tools/commit-tree.py
It rewrites docs/commits.md in place, so it is safe to run whenever the
history has moved on. Nothing else reads the file; it is for reading.
"""
import subprocess, sys, os, collections

NL = chr(10)
SEP = chr(31)   # unit separator: cannot appear in a commit subject


def git(*args):
    root = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                          capture_output=True, text=True).stdout.strip()
    out = subprocess.run(["git"] + list(args), capture_output=True, text=True,
                         cwd=root, encoding="utf-8", errors="replace")
    return out.stdout.rstrip(NL), root


fmt = SEP.join(["%h", "%ad", "%an", "%s"])
log, root = git("log", "--date=short", "--format=" + fmt)
graph, _ = git("log", "--graph", "--date=short",
               "--format=%h %ad  %s", "-40")
total, _ = git("rev-list", "--count", "HEAD")
head, _ = git("log", "-1", "--format=%h %s")
branch, _ = git("rev-parse", "--abbrev-ref", "HEAD")

rows = []
for line in log.split(NL):
    if not line.strip():
        continue
    parts = line.split(SEP)
    if len(parts) == 4:
        rows.append(parts)

by_month = collections.OrderedDict()
per_day = collections.Counter()
authors = collections.Counter()
for h, d, a, s in rows:
    by_month.setdefault(d[:7], []).append((h, d, a, s))
    per_day[d] += 1
    authors[a] += 1

busiest = per_day.most_common(1)[0] if per_day else ("--", 0)

out = []
out.append("# The commit tree")
out.append("")
out.append("Generated by `tools/commit-tree.py` -- re-run it to refresh.")
out.append("Newest first.")
out.append("")
out.append("| | |")
out.append("|---|---|")
out.append("| commits | **" + total + "** |")
out.append("| first | " + (rows[-1][1] if rows else "--") + " |")
out.append("| latest | " + (rows[0][1] if rows else "--") + " |")
out.append("| branch | `" + branch + "` |")
out.append("| head | `" + head + "` |")
out.append("| busiest day | " + busiest[0] + " (" + str(busiest[1]) + " commits) |")
out.append("")
out.append("## Shape of the last forty")
out.append("")
out.append("```")
out.append(graph)
out.append("```")
out.append("")
out.append("## Every commit, by month")
out.append("")
for month, items in by_month.items():
    out.append("### " + month + "  ·  " + str(len(items)) + " commits")
    out.append("")
    day = None
    for h, d, a, s in items:
        if d != day:
            out.append("**" + d + "**")
            out.append("")
            day = d
        out.append("- `" + h + "` " + s)
    out.append("")

docs = os.path.join(root, "docs")
os.makedirs(docs, exist_ok=True)
path = os.path.join(docs, "commits.md")
with open(path, "w", encoding="utf-8", newline=NL) as f:
    f.write(NL.join(out) + NL)
print("wrote " + path + "  (" + total + " commits, " + str(len(by_month)) + " months)")
