"""Generate a BIRCH tree as a .vox model, at the game's 10 cm voxel scale.

    python tools/gen_birch.py                      -> game/assets/decoration/birch.vox
    python tools/gen_birch.py --seed 7 --out x.vox

WHY GENERATE RATHER THAN AUTHOR. Every other tree in this game is baked art (pine5.vox, oak_trees.json). A
birch is the one shape worth generating instead: its whole character is a RULE — a slender white stem with
black lash marks, branches that leave the trunk high and sweep up, and a canopy that is mostly holes. Those
are three lines of arithmetic each, and a generator can be re-rolled for variants where a hand-authored model
would have to be redrawn.

THE SCALE IS THE POINT. A voxel is 10 cm, so a 5.6 m birch is 56 voxels tall and a 30 cm stem is 3 wide. Every
number below is written as METRES and converted once, so the model can be re-scaled by changing one constant
rather than by re-tuning twenty.

WHAT MAKES IT READ AS A BIRCH, in the order the eye picks it up:
  1. BARK. Near-white, and the marks are HORIZONTAL — that is the single strongest cue. They are short dashes
     wrapping part of the circumference, denser low down where a real birch is scarred, thinning as the stem
     gets young and pale toward the crown. Vertical marks would read as pine.
  2. SLENDERNESS. The stem tapers from 1.6 to 0.55 voxels of radius. Birches are thin; a fat white trunk reads
     as aspen or as a dead pine.
  3. AN OPEN CROWN. Leaves are placed as ellipsoid clusters at and along the outer half of each branch, then
     THINNED by a hash to about half density. A solid canopy reads as oak. The holes are the species.
  4. BRANCHES THAT START HIGH. Nothing below 45% of the height, which is what gives a birch its bare, clean
     lower stem.

Deterministic: a small integer hash, not `random`, so the same seed always yields the same tree and a variant
set can be generated by seed rather than stored.

Stdlib only; run with the plain `python` on PATH.
"""
import math, os, struct, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VOX_M = 0.10                                          # one voxel = 10 cm; every dimension below is in METRES


def h2(a, b, seed):
    """Deterministic 0..1 from two integers. Cheap integer mix, then a float in [0,1)."""
    n = (a * 73856093) ^ (b * 19349663) ^ (seed * 83492791)
    n &= 0x7fffffff
    n = (n ^ (n >> 13)) * 1274126177
    n &= 0x7fffffff
    return ((n ^ (n >> 16)) & 0xffff) / 65536.0


def build(seed=1, H_M=5.6):                            # H_M: total height in metres — the ONE number that re-scales a tree
    R0_M, R1_M = 0.19, 0.075                           # stem radius at base and crown. Bumped from 0.16/0.055: at 10 cm a 0.055 m radius is barely one voxel and the mid-stem read as a wire
    H = int(round(H_M / VOX_M))                        # 56 voxels at the default 5.6 m
    scale = H_M / 5.6                                  # everything below is authored against a 5.6 m tree and scaled from it
    vox = {}                                           # (x, y, z) -> palette index

    # ── PALETTE ── indices are 1-based, exactly as MagicaVoxel stores them.
    #  1-3 papery bark, light to shadowed   4-5 the dark lash marks   6 the warm scarred base
    #  7-10 leaves, light to deep
    pal = [(238, 238, 232), (223, 223, 214), (204, 205, 195),
           (58, 56, 52), (88, 84, 78),
           (176, 166, 150),
           (150, 190, 98), (126, 168, 74), (104, 146, 60), (86, 124, 48)]
    BARK_L, BARK_M, BARK_D, MARK_D, MARK_M, BASE = 1, 2, 3, 4, 5, 6
    LEAF = (7, 8, 9, 10)

    # ── THE STEM ── a gentle sinuous lean rather than a ruler-straight pole. Two slow sines on different
    # periods so the curve never repeats within the tree's own height and never reads as a spiral.
    def stem_xy(z):
        t = z / H
        return (math.sin(t * 2.1 + seed) * 1.5 + math.sin(t * 4.7 + seed * 2) * 0.6,
                math.cos(t * 1.7 + seed * 3) * 1.4 + math.cos(t * 3.9 + seed) * 0.5)

    def radius(z):
        t = z / H
        r = (R0_M + (R1_M - R0_M) * (t ** 0.72)) / VOX_M   # ^0.72: a birch keeps its width low and then narrows fast
        return r + (0.9 if t < 0.05 else 0.0)              # a slight root flare in the bottom half-metre

    for z in range(H):
        cx, cy = stem_xy(z)
        r = radius(z)
        rr = int(math.ceil(r)) + 1
        for dx in range(-rr, rr + 1):
            for dy in range(-rr, rr + 1):
                d = math.hypot(dx - (cx - round(cx)), dy - (cy - round(cy)))
                if d > r:
                    continue
                x, y = int(round(cx)) + dx, int(round(cy)) + dy
                t = z / H
                # ── THE LASH MARKS ── horizontal dashes: a band is chosen per z, and within a band only part of
                # the circumference is painted, so each mark wraps the stem instead of ringing it completely.
                ang = math.atan2(dy, dx)
                band = h2(z, 0, seed) < (0.58 - 0.30 * t)      # denser low, sparse and pale near the crown. 0.34 -> 0.58: the marks are the single strongest birch cue and three of them over six metres read as a dirty aspen
                arc = h2(z, 1, seed) * 6.283
                wide = 0.7 + h2(z, 2, seed) * 1.5              # how far round this particular dash reaches
                on_arc = abs(((ang - arc + math.pi) % 6.283) - math.pi) < wide
                if t < 0.06:
                    c = BASE                                    # scarred, weathered foot
                elif band and on_arc:
                    c = MARK_D if h2(z, x * 7 + y, seed) < 0.75 else MARK_M
                else:
                    # shade by facing so the cylinder reads round rather than flat
                    c = BARK_L if dx + dy < -r * 0.3 else (BARK_D if dx + dy > r * 0.5 else BARK_M)
                vox[(x, y, z)] = c

    # ── BRANCHES ── none below 45% of the height, which is what leaves a birch its clean bare stem. They
    # alternate around the trunk by golden angle so no two sit above each other, and they SWEEP: the tip rises
    # more steeply than the base, which is the birch's lift.
    nb = 9
    tips = []
    for i in range(nb):
        t = 0.45 + 0.52 * (i / max(1, nb - 1))
        z0 = int(t * H)
        ang = i * 2.399963 + seed                      # golden angle, so successive branches never line up
        length = (1.15 - 0.75 * t) / VOX_M * (0.75 + h2(i, 9, seed) * 0.5) * scale   # * scale: branch reach is a fraction of the TREE, not an absolute — without it a 3.2 m sapling grew a 7.4 m tree's limbs
        bx, by = stem_xy(z0)
        steps = int(length * 1.5) + 3
        for s in range(steps):
            u = s / (steps - 1)
            rr = u * length
            zz = z0 + rr * (0.35 + 0.75 * u)           # sweeping upward, steeper toward the tip
            x = int(round(bx + math.cos(ang) * rr))
            y = int(round(by + math.sin(ang) * rr))
            z = int(round(zz))
            if z >= H + 10:
                break
            thick = 1 if u < 0.45 else 0
            for ox in range(-thick, thick + 1):
                for oy in range(-thick, thick + 1):
                    vox.setdefault((x + ox, y + oy, z), BARK_M if u < 0.6 else BARK_L)
            if u > 0.42:
                tips.append((x, y, z, u))

    # ── THE CROWN ── clusters on the outer half of every branch, then thinned. The thinning is the species: a
    # solid shell reads as an oak, and it is the holes that make a birch look light.
    for (x, y, z, u) in tips:
        rad = (2.1 + 2.3 * u + h2(x, y, seed) * 1.2) * scale   # …and the crown with it, or every tree in a grove ends up the same size whatever its stem says
        ri = int(math.ceil(rad))
        for dx in range(-ri, ri + 1):
            for dy in range(-ri, ri + 1):
                for dz in range(-ri, ri + 1):
                    # squashed vertically: birch foliage hangs in flattish sprays, not spheres
                    d = math.sqrt(dx * dx + dy * dy + (dz * 1.55) ** 2)
                    if d > rad:
                        continue
                    px, py, pz = x + dx, y + dy, z + dz
                    if pz < 4 or (px, py, pz) in vox:
                        continue
                    if h2(px * 3 + pz, py * 5 - pz, seed) > 0.46 - 0.18 * (d / rad):
                        continue                        # ~half density, thinning further at the cluster edge
                    k = h2(px, py * 2 + pz, seed)
                    vox[(px, py, pz)] = LEAF[0] if k < 0.22 else LEAF[1] if k < 0.58 else LEAF[2] if k < 0.86 else LEAF[3]

    return vox, pal


def write_vox(path, vox, pal):
    xs = [p[0] for p in vox]; ys = [p[1] for p in vox]; zs = [p[2] for p in vox]
    lo = (min(xs), min(ys), min(zs))
    sx, sy, sz = max(xs) - lo[0] + 1, max(ys) - lo[1] + 1, max(zs) - lo[2] + 1
    if max(sx, sy, sz) > 255:
        raise SystemExit('model %dx%dx%d exceeds the .vox 255 limit' % (sx, sy, sz))
    data = b''.join(bytes((p[0] - lo[0], p[1] - lo[1], p[2] - lo[2], c)) for p, c in vox.items())
    rgba = bytearray(1024)
    for i, c in enumerate(pal):
        o = i * 4
        rgba[o], rgba[o + 1], rgba[o + 2], rgba[o + 3] = c[0], c[1], c[2], 255

    def chunk(cid, content, children=b''):
        return cid + struct.pack('<II', len(content), len(children)) + content + children
    body = (chunk(b'SIZE', struct.pack('<III', sx, sy, sz))
            + chunk(b'XYZI', struct.pack('<I', len(vox)) + data)
            + chunk(b'RGBA', bytes(rgba)))
    open(path, 'wb').write(b'VOX ' + struct.pack('<I', 150) + chunk(b'MAIN', b'', body))
    return sx, sy, sz


def grove(heights, seed=1, gap=4):
    """Several birches side by side in ONE model.

    The asset editor stages a single .vox, and its two lanes are for comparing a model against a preview — not
    for showing four of anything. So a grove is one model with the trees laid out along x, which also means the
    editor centres the whole stand rather than one tree of it.

    Laid out by each tree's OWN measured width rather than a fixed pitch: a 7.4 m birch carries a crown half as
    wide again as a 3.2 m one, and a fixed pitch would either overlap the big ones or strand the small ones in
    space. Each is measured, placed, and the cursor advances by that width plus a gap.
    """
    out, pal, cursor = {}, None, 0
    for i, h in enumerate(heights):
        v, pal = build(seed + i * 17, h)               # a different seed per tree, or four identical trees at four scales
        xs = [p[0] for p in v]; ys = [p[1] for p in v]; zs = [p[2] for p in v]
        lox, loy, loz = min(xs), min(ys), min(zs)
        w = max(xs) - lox + 1
        for (x, y, z), c in v.items():
            out[(x - lox + cursor, y - loy, z - loz)] = c
        cursor += w + gap
    return out, pal


def main():
    seed, out = 1, os.path.join(ROOT, 'game', 'assets', 'decoration', 'birch.vox')
    for i, a in enumerate(sys.argv[1:]):
        if a == '--seed':
            seed = int(sys.argv[i + 2])
        elif a == '--out':
            out = sys.argv[i + 2] if os.path.isabs(sys.argv[i + 2]) else os.path.join(ROOT, sys.argv[i + 2])
    # ── FOUR TREES, FOUR SIZES (user 2026-08-18) ── 3.2 to 7.4 m, which at 10 cm is 32 to 74 voxels: a sapling,
    # two mid stems and one full-grown. Spread evenly so the taper, the branch height and the crown density can
    # all be judged against each other on one stage.
    # ── SIZED TO THE EDITOR STAGE, NOT TO A REAL BIRCH ── the stage sits between the terrain under it and the
    # world ceiling, and how much room that leaves is decided by whatever happens to be below: measured between
    # 46 and ~158 voxels. A 7.4 m tree (81 voxels with its crown) was being cut off at the waist. 2.0-4.4 m is a
    # stand of saplings rather than mature trees, but it FITS in the worst case, which is what makes it visible.
    # For a full-height birch to drop into the world, generate one on its own: --seed N with grove() bypassed.
    # ── THE ORIGINAL IS THE SMALLEST, THE REST SCALE UP (user 2026-08-18) ── 5.6 m is the tree this generator
    # was first tuned against, so it stays the reference and the other three grow from it. A 9.2 m birch is a
    # mature stand-alone specimen; at 10 cm that is 92 voxels of stem plus its crown.
    vox, pal = grove([5.6, 6.8, 8.0, 9.2], seed)
    sx, sy, sz = write_vox(out, vox, pal)
    leaves = sum(1 for c in vox.values() if c >= 7)
    print('%s  %dx%dx%d  %d voxels (%d bark, %d leaf)  = %.1f m tall at %d cm per voxel'
          % (os.path.relpath(out, ROOT), sx, sy, sz, len(vox), len(vox) - leaves, leaves,
             sz * VOX_M, int(VOX_M * 100)))


main()
